base.url=https://reqres.in
endpoint.create.user=/api/users
endpoint.get.user.by.id=/api/users/{id}
endpoint.update.user=/api/users/{id}
endpoint.delete.user=/api/users/{id}
auth.token=dummy-token-for-framework
api.key=reqres-free-v1
